import React from 'react';
import {
  Bike,
  Layers,
  TrendingUp,
  Maximize2,
  GripVertical,
  Waves,
  Minus,
  ArrowBigDown,
  Footprints,
  RefreshCw,
  ArrowBigUp,
  ArrowUp,
  ChevronUp,
  Undo2,
  Link2,
  Shield,
  Slash,
  LayoutGrid,
  Download,
  ArrowLeftRight,
  GitFork,
  ScanLine,
  Bug,
  MoveVertical,
  Mountain,
  Wind,
  Hammer,
  RotateCw,
  Zap,
  Box,
  Sofa,
  Dumbbell,
} from 'lucide-react';

const FRAME =
  'shrink-0 w-14 h-14 rounded-xl border border-violet-500/40 bg-gradient-to-br from-slate-800/96 to-slate-950 shadow-inner flex items-center justify-center text-violet-200 ring-1 ring-white/5';

export const SPLIT_POSE_BY_EX_ID = {
  sp_ch_0: 'bike',
  sp_ch_1: 'bench',
  sp_ch_2: 'benchIncline',
  sp_ch_3: 'fly',
  sp_ch_4: 'dipBars',
  sp_ch_ab1: 'crunch',
  sp_ch_ab2: 'plank',
  sp_ch_lg1: 'squat',
  sp_ch_lg2: 'lunge',
  sp_sh_0: 'armCircle',
  sp_sh_1: 'ohp',
  sp_sh_2: 'latRaise',
  sp_sh_3: 'rearFly',
  sp_sh_4: 'ropePull',
  sp_sh_ab1: 'pallof',
  sp_sh_ab2: 'sidePlank',
  sp_sh_lg1: 'legPush',
  sp_sh_lg2: 'calfUp',
  sp_bk_0: 'spinal',
  sp_bk_1: 'latPull',
  sp_bk_2: 'rowCable',
  sp_bk_3: 'rowOne',
  sp_bk_4: 'hyperExt',
  sp_bk_ab1: 'kneeUp',
  sp_bk_ab2: 'deadBug',
  sp_bk_lg1: 'hinge',
  sp_bk_lg2: 'bridgeHam',
  sp_ar_0: 'warmArm',
  sp_ar_1: 'curl',
  sp_ar_2: 'hammer',
  sp_ar_3: 'triPush',
  sp_ar_4: 'triOverhead',
  sp_ar_ab1: 'twist',
  sp_ar_ab2: 'runner',
  sp_ar_lg1: 'squatFront',
  sp_ar_lg2: 'calfSit',
};

const POSE_ICON = {
  bike: Bike,
  bench: Layers,
  benchIncline: TrendingUp,
  fly: Maximize2,
  dipBars: GripVertical,
  crunch: Waves,
  plank: Minus,
  squat: ArrowBigDown,
  lunge: Footprints,
  armCircle: RefreshCw,
  ohp: ArrowBigUp,
  latRaise: ChevronUp,
  rearFly: Undo2,
  ropePull: Link2,
  pallof: Shield,
  sidePlank: Slash,
  legPush: LayoutGrid,
  calfUp: ArrowBigUp,
  spinal: Waves,
  latPull: Download,
  rowCable: ArrowLeftRight,
  rowOne: GitFork,
  hyperExt: ScanLine,
  kneeUp: ArrowUp,
  deadBug: Bug,
  hinge: MoveVertical,
  bridgeHam: Mountain,
  warmArm: Wind,
  curl: Undo2,
  hammer: Hammer,
  triPush: ArrowBigDown,
  triOverhead: ArrowBigUp,
  twist: RotateCw,
  runner: Zap,
  squatFront: Box,
  calfSit: Sofa,
};

export default function SplitPoseThumb({ exerciseId }) {
  const key = SPLIT_POSE_BY_EX_ID[exerciseId];
  const Cmp = POSE_ICON[key] || Dumbbell;
  return (
    <div className={FRAME} aria-hidden>
      <Cmp className="w-7 h-7" strokeWidth={1.55} />
    </div>
  );
}
